version: '3.8'

services:
  cms:
    build: .
    image: cms:latest
    container_name: cms
    ports:
      - "8080:8080"
    volumes:
      - /app/cms/file:/app/cms/file
      - /app/cms/logs:/app/cms/logs
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
